
#
#	Global configuration for SNAP makefiles
#

GLIB = glib-core
SNAP = snap-core
GLIBADV = glib-adv
SNAPADV = snap-adv
SNAPEXP = snap-exp

CGLIB = $(SNAP_DIR)/examples/$(GLIB)
CSNAP = $(SNAP_DIR)/examples/$(SNAP)

EXGLIB = $(SNAP_DIR)/$(GLIB)
EXSNAP = $(SNAP_DIR)/$(SNAP)
EXGLIBADV = $(SNAP_DIR)/$(GLIBADV)
EXSNAPADV = $(SNAP_DIR)/$(SNAPADV)
EXSNAPEXP = $(SNAP_DIR)/$(SNAPEXP)

UNAME := $(shell uname)

ifeq ($(UNAME), Linux)
  # Linux flags
  CC = g++

 # CXXFLAGS += -std=c++98 -Wall

  CXXFLAGS += -std=c++11 -Wall
  CXXFLAGS += -O3 -DNDEBUG -fopenmp
  # turn on for crash debugging, get symbols with <prog> 2>&1 | c++filt
  #CXXFLAGS += -g -rdynamic
  #CXXFLAGS += -ggdb
  # turn on for OpenMP
  #CXXOPENMP = -fopenmp
  LDFLAGS +=
  LIBS += -lrt

else ifeq ($(UNAME), Darwin)
  # OS X flags
  #CC = g++
  CC = g++-7

  # CXXFLAGS += -std=c++98 -Wall
  # CXXFLAGS += -std=c++11 -Wall -fsanitize=undefined

  CXXFLAGS += -std=c++11 -Wall
  CXXFLAGS += -O3 -DNDEBUG

  # Enable the below flags and comment the above flag to use gdb
  # CXXFLAGS += -g3 -DNDEBUG

  CLANG := $(shell g++-7 -v 2>&1 | grep clang | cut -d " " -f 2)
  ifneq ($(CLANG), LLVM)
    CXXFLAGS += -fopenmp
    #CXXOPENMP += -fopenmp
  else
    CXXFLAGS += -DNOMP
    CXXOPENMP =
  endif
  LDFLAGS +=
  LIBS +=

else ifeq ($(shell uname -o), Cygwin)
  # Cygwin flags
  CC = g++
  CXXFLAGS += -Wall -D__STDC_LIMIT_MACROS
  CXXFLAGS += -O3 -DNDEBUG
  CXXOPENMP = -fopenmp
  LDFLAGS +=
  LIBS +=

endif
